name = "primalprinting-pdf-processor"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[r2_buckets]]
binding = "STAGING_BUCKET"
bucket_name = "primalprinting-staging"

[[queues.consumers]]
queue = "primalprinting-pdf-page-count"
max_batch_size = 10
max_retries = 3
max_batch_timeout = 5
